DELETE http://localhost:3003/api/blogs/6464ab3b2b066705a33ecbf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjY0MmQ5NmRjZjY3MzdiMTE1OWM0NTljOCIsImlhdCI6MTY4NDMxOTA3MSwiZXhwIjoxNjg0MzIyNjcxfQ.T4xDUHxqZC_ZYyBZeoxJP4a_K-ox7lB17k60lS4agUQ