PUT http://localhost:3003/api/blogs/like/641e1f9df906771660c34590
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjY0MWYyMWE0OTgyOTUyNTIwZmJhODAyYSIsImlhdCI6MTY3OTc2MTg0OCwiZXhwIjoxNjc5NzY1NDQ4fQ.ZY1Gw_H2YCpaQnJJ-m32Ma5C3WdUxuWrR8bY257EXQ0

{
    "vote": 0
}